In [1]:
import numpy as np
import pandas as pd

In [3]:
data = pd.read_csv('yelp.csv')
data.head(2)

business_id        date               review_id  stars  \
0  9yKzy9PApeiPPOUJEtnvkg  2011-01-26  fWKvX83p0-ka4JS3dc6E5A      5   
1  ZRJwVLyzEJq1VAihDhYiow  2011-07-27  IjZ33sJrzXqU-0X6U8NwyA      5   

                                                text    type  \
0  My wife took me here on my birthday for breakf...  review   
1  I have no idea why some people give bad review...  review   

                  user_id  cool  useful  funny  
0  rLtl8ZkDX5vH5nAx9C3q5Q     2       5      0  
1  0a2KyEL0d3Yb1V6aivbIuQ     0       0      0

In [5]:
data.shape

(10000, 10)

In [6]:
data.stars.unique()

array([5, 4, 2, 3, 1], dtype=int64)

In [ ]:
# label = stars
# feature  = text

In [7]:
feature = data[['text']]
label = data['stars']

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(feature, label, test_size=0.2, random_state=1)


In [13]:
X_train.head(3)

text
2694  Great girls night out place.  Wine selection w...
5140  I love their strawberry drink, its not really ...
2568  Amazing selection of beers with great tabs edu...

In [14]:
y_train.head(3)

2694    4
5140    4
2568    5
Name: stars, dtype: int64

# Clean up 1 message

In [16]:
sentence = X_train.iloc[0,0]
sentence

'Great girls night out place.  Wine selection was extensive and we DEVOURED the Bruschetta!  Try to get there for the Happy Hour prices or you will be paying a minimum of $9 per glass of wine.  \nOne of my new fave places :)'

In [17]:
# here we import two liberaries.
#  1. string for work on string.
#     1.1 we import string libarary for remove punctuation(special) words
#           like ===== '!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~' =============
#  2. we import nltk package for remove stop words
import string
from nltk.corpus import stopwords

In [18]:
removepunctuation = [ char for char in sentence if char not in string.punctuation+"0123456789" ]
removepunctuation                                       

['G',
 'r',
 'e',
 'a',
 't',
 ' ',
 'g',
 'i',
 'r',
 'l',
 's',
 ' ',
 'n',
 'i',
 'g',
 'h',
 't',
 ' ',
 'o',
 'u',
 't',
 ' ',
 'p',
 'l',
 'a',
 'c',
 'e',
 ' ',
 ' ',
 'W',
 'i',
 'n',
 'e',
 ' ',
 's',
 'e',
 'l',
 'e',
 'c',
 't',
 'i',
 'o',
 'n',
 ' ',
 'w',
 'a',
 's',
 ' ',
 'e',
 'x',
 't',
 'e',
 'n',
 's',
 'i',
 'v',
 'e',
 ' ',
 'a',
 'n',
 'd',
 ' ',
 'w',
 'e',
 ' ',
 'D',
 'E',
 'V',
 'O',
 'U',
 'R',
 'E',
 'D',
 ' ',
 't',
 'h',
 'e',
 ' ',
 'B',
 'r',
 'u',
 's',
 'c',
 'h',
 'e',
 't',
 't',
 'a',
 ' ',
 ' ',
 'T',
 'r',
 'y',
 ' ',
 't',
 'o',
 ' ',
 'g',
 'e',
 't',
 ' ',
 't',
 'h',
 'e',
 'r',
 'e',
 ' ',
 'f',
 'o',
 'r',
 ' ',
 't',
 'h',
 'e',
 ' ',
 'H',
 'a',
 'p',
 'p',
 'y',
 ' ',
 'H',
 'o',
 'u',
 'r',
 ' ',
 'p',
 'r',
 'i',
 'c',
 'e',
 's',
 ' ',
 'o',
 'r',
 ' ',
 'y',
 'o',
 'u',
 ' ',
 'w',
 'i',
 'l',
 'l',
 ' ',
 'b',
 'e',
 ' ',
 'p',
 'a',
 'y',
 'i',
 'n',
 'g',
 ' ',
 'a',
 ' ',
 'm',
 'i',
 'n',
 'i',
 'm',
 'u',
 'm',
 ' ',
 'o',
 'f'

In [20]:
sentance2 = ''.join(removepunctuation)
sentance2    

'Great girls night out place  Wine selection was extensive and we DEVOURED the Bruschetta  Try to get there for the Happy Hour prices or you will be paying a minimum of  per glass of wine  \nOne of my new fave places '

In [23]:
from nltk.corpus import stopwords

In [24]:
print(stopwords.words("english"))

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [26]:
sentance2 =  sentance2.split()
sentance2

['Great',
 'girls',
 'night',
 'out',
 'place',
 'Wine',
 'selection',
 'was',
 'extensive',
 'and',
 'we',
 'DEVOURED',
 'the',
 'Bruschetta',
 'Try',
 'to',
 'get',
 'there',
 'for',
 'the',
 'Happy',
 'Hour',
 'prices',
 'or',
 'you',
 'will',
 'be',
 'paying',
 'a',
 'minimum',
 'of',
 'per',
 'glass',
 'of',
 'wine',
 'One',
 'of',
 'my',
 'new',
 'fave',
 'places']

In [27]:
print(sentance2)

['Great', 'girls', 'night', 'out', 'place', 'Wine', 'selection', 'was', 'extensive', 'and', 'we', 'DEVOURED', 'the', 'Bruschetta', 'Try', 'to', 'get', 'there', 'for', 'the', 'Happy', 'Hour', 'prices', 'or', 'you', 'will', 'be', 'paying', 'a', 'minimum', 'of', 'per', 'glass', 'of', 'wine', 'One', 'of', 'my', 'new', 'fave', 'places']


In [28]:
[word.lower() for word in sentance2 if word.lower() not in stopwords.words("english") ]

['great',
 'girls',
 'night',
 'place',
 'wine',
 'selection',
 'extensive',
 'devoured',
 'bruschetta',
 'try',
 'get',
 'happy',
 'hour',
 'prices',
 'paying',
 'minimum',
 'per',
 'glass',
 'wine',
 'one',
 'new',
 'fave',
 'places']

# To clean up all the messages

In [31]:
a = string.punctuation + "0123456789"


In [32]:
def text_clean(sentance):
    p = [char for char in sentance if char not in a]
    p = ''.join(p)
    q = [word.lower() for word in p.split() if word.lower() not in stopwords.words("english")]
    
    return(q)

In [33]:
X_train.text.apply(text_clean)

2694    [great, girls, night, place, wine, selection, ...
5140    [love, strawberry, drink, really, agua, fresca...
2568    [amazing, selection, beers, great, tabs, educa...
3671    [park, always, pleasant, experience, honey, li...
7427    [giving, restaurant, four, stars, must, start,...
                              ...                        
2895    [wait, secondi, written, review, nuts, anyways...
7813    [far, best, farmers, market, ive, valley, stil...
905     [facility, bit, dated, service, great, dr, rio...
5192    [lot, things, miss, socal, one, things, rich, ...
235     [used, frequent, lost, leaf, almost, daily, st...
Name: text, Length: 8000, dtype: object

In [34]:
#Prepare our feature compatible for ML algorithm
#Sklearn helps you to achieve this target
# text Features ====> BagOfWords ===> TF-IDF ===> Freq ==> Feature Array

from sklearn.feature_extraction.text import CountVectorizer

In [35]:
bow = CountVectorizer(analyzer = text_clean)

In [36]:
# BagOfWords : create dictionary which contain text and it's counts.
# like: (hello,272234)
bow.fit(X_train["text"])

CountVectorizer(analyzer=<function text_clean at 0x000001EE79F85C18>,
                binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [37]:
# convert count info frequency between (0-1) 
msg_bows=bow.transform(X_train.text)

In [38]:
msg_bows

<8000x31188 sparse matrix of type '<class 'numpy.int64'>'
	with 454566 stored elements in Compressed Sparse Row format>

In [39]:
msg_bows.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [40]:
msg_bows.shape

(8000, 31188)

In [41]:
#Create Model
from sklearn.naive_bayes import MultinomialNB #Best for Text Data Features
X_train = msg_bows
nb = MultinomialNB()

In [42]:
nb.fit(X_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [43]:
type(X_train)

scipy.sparse.csr.csr_matrix

In [45]:
nb.score(X_train, y_train)

0.786375

In [46]:
X_test[:2]

text
9953  "Hipster,Trendy" ????-I think NOT !!!! Very di...
3850  My husband & I have been going to one Zipp's o...

In [47]:
test_bows = bow.transform(X_test.text)

In [48]:
# create two dimessional array
test_bows.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [50]:
ypred = nb.predict(test_bows)

In [51]:
ypred

array([4, 4, 5, ..., 1, 3, 4], dtype=int64)

In [52]:
nb.score(test_bows, ypred)

1.0

# model testing

In [57]:

test_bows = bow.transform([["this is awesome"],["this is time worst"],["i love it"]])
test_bows.toarray()
nb.predict(test_bows)

array([5, 1, 5], dtype=int64)