# Numpy - Array and Matrix Creation


In [1]:
# What is numpy?
# Its an external package used to work with arrays (ndarrays)
# Array is a collection of similar elements
#
# Import the numpy package

In [2]:
import numpy as np

In [3]:
# Create a One Dimensional Array

list1 = [1,2,3,4,5,6]

oneDimExample = np.array(list1)

In [4]:
oneDimExample

array([1, 2, 3, 4, 5, 6])

In [5]:
oneDimExample.ndim #Displays the number of dimensions

1

In [6]:
oneDimExample.shape

(6,)

In [7]:
type(oneDimExample)

numpy.ndarray

In [8]:
#Create a two dimensional array

In [9]:
twoDimExample = np.array([[1,2,3],
                         [4,5,6],
                         [7,8,9]])

In [10]:
twoDimExample

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
twoDimExample.ndim

2

In [12]:
twoDimExample.shape

(3, 3)

In [13]:
type(twoDimExample)

numpy.ndarray

In [14]:
# Big difference between Matrix and Array
# =============================================
# 
# You can create Matrix(np.matrix()) and Array(np.array()) using Numpy. 
#
# Array
twoDimArray = np.array([[1,2,3],
                         [4,5,6],
                         [7,8,9]])

twoDimMatrix = np.matrix([[1,2,3],
                         [4,5,6],
                         [7,8,9]])

In [15]:
# Perform Multiplication of the array
#
# Multiplication of an array is element-wise multiplication
#
#   1 2 3      1 2 3       (1*1) (2*2) (3*3)
#   4 5 6   *  4 5 6   =   (4*4) (5*5) (6*6)
#   7 8 9      7 8 9       (7*7) (8*8) (9*9)

resultArray = twoDimArray * twoDimArray
resultArray

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [16]:
# Perform Multiplication of the matrix
#
# 

resultMatrix = twoDimMatrix * twoDimMatrix
resultMatrix

matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [17]:
# Numpy Array Operation
#
# Arithmetic Operations ---> +,-,*,/,%,**

In [18]:
resultAddition = twoDimArray + twoDimArray
resultAddition

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [19]:
resultSub = twoDimArray - twoDimArray
resultSub

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [20]:
resultMul = twoDimArray * twoDimArray
resultMul

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [21]:
resultDiv = twoDimArray / twoDimArray
resultDiv

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
increaseBy2 = twoDimArray ** 2
increaseBy2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

In [23]:
list(increaseBy2)

[array([1, 4, 9], dtype=int32),
 array([16, 25, 36], dtype=int32),
 array([49, 64, 81], dtype=int32)]

In [24]:
increaseBy2.tolist()

[[1, 4, 9], [16, 25, 36], [49, 64, 81]]

# Built-In Function on Numpy


In [25]:
import numpy as np

In [26]:
# arange - Returns evenly spaced values with a given interval
#
# np.arange(start_value, upperbound, stepSize)

In [27]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [29]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [30]:
# Zeros and Ones

In [31]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [33]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [34]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [35]:
# linspace -- Returns evenly spaced numbers over a specified interval

In [36]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [37]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [38]:
# Eye --- Identity Array

In [39]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
np.matrix(np.eye(6))

matrix([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]])

In [41]:
#Random -- To generate random numbers

In [42]:
# Rand returns uniform distribution data
# Uniform Distribution means all your data will be generated within the range of 0,1
np.random.rand(10) 

array([0.18589441, 0.60917364, 0.71541432, 0.77841715, 0.38206322,
       0.35926052, 0.67190291, 0.7325814 , 0.60453638, 0.25130601])

In [43]:
#randn returns Normal Distribution data
# The mean of the values are 0 and Standard Dev of values are 1
np.random.randn(10)

array([-1.19074394, -0.83128022,  2.18121229, -1.07690632, -0.22332154,
       -0.42224976, -0.29013548, -0.42998772,  1.13168055, -0.7776274 ])

In [44]:
data = np.random.randn(10)
print(np.mean(data))
print(np.std(data))

0.042522227375353085
0.8864199240230755


In [45]:
#Returns only integer values wiithin the range specified
# randint( startrange, endrange, number of elements)
np.random.randint(1,100,1)

array([52])

In [46]:
np.random.randint(1,100,10)

array([31, 32, 53, 26, 33, 20, 13, 92, 45, 68])

In [47]:
# Finding Min,Max,IndexMin,IndexMax

In [48]:
array1 = np.array([4,2,5,2,78,9,900,234,567,2,1])

In [49]:
array1.max() #max value in the array

900

In [50]:
array1.argmax() #index location of the max value

6

In [51]:
array1.min()

1

In [52]:
array1.argmin()

10

In [53]:
np.max(array1)

900

In [54]:
np.min(array1)

1

In [55]:
np.argmax(array1)

6

In [56]:
np.argmin(array1)

10

# Changing Dimensions of Array


In [57]:
# reshape -- Allows you to convert 1d to 2d

In [58]:
data = np.random.randint(1,100,9)

In [59]:
data

array([42, 61, 17, 25, 23, 96, 54, 92, 65])

In [60]:
data.ndim

1

In [61]:
data = data.reshape(3,3)

In [62]:
data.reshape(1,9)

array([[42, 61, 17, 25, 23, 96, 54, 92, 65]])

In [63]:
data.reshape(9,1)

array([[42],
       [61],
       [17],
       [25],
       [23],
       [96],
       [54],
       [92],
       [65]])

In [64]:
data

array([[42, 61, 17],
       [25, 23, 96],
       [54, 92, 65]])

In [65]:
# Ravel --- Convert 2d to 1d

In [66]:
data.ndim

2

In [67]:
data

array([[42, 61, 17],
       [25, 23, 96],
       [54, 92, 65]])

In [68]:
data.ravel()

array([42, 61, 17, 25, 23, 96, 54, 92, 65])

In [69]:
data.ravel().ndim

1

# Selecting Elements in Array


In [70]:
data1 = np.random.randint(1,100,9)

In [71]:
data1

array([77, 48, 93, 99, 41, 20, 34, 73, 20])

In [72]:
data1[6]

34

In [73]:
data1[2:6]

array([93, 99, 41, 20])

In [74]:
data2 = data1.reshape(3,3)
data2

array([[77, 48, 93],
       [99, 41, 20],
       [34, 73, 20]])

In [75]:
#Row and Column Index starts from 0

In [76]:
data2[0,0]

77

In [77]:
data2[2,2]

20

In [78]:
data2[1 , 1:3]

array([41, 20])

In [79]:
data2[0:2 , 1:3]

array([[48, 93],
       [41, 20]])

In [80]:
#     row_index    col_index
# 86   0             0
# 70   0             2
# 96   2             0
# 48   2             2

In [81]:
#Fancy Indexing

data2[[0,0,2,2],[0,2,0,2]].reshape(2,2)

array([[77, 93],
       [34, 20]])

In [82]:
data2

array([[77, 48, 93],
       [99, 41, 20],
       [34, 73, 20]])

In [83]:
#54,26,73,96
data2[[1, 1, 0, 2],[0, 1, 1, 0]]

array([99, 41, 48, 34])

# Searching Elements

In [84]:
data1 = np.random.randint(1,200,9)
data1

array([  4,  54,  63, 173,  42,  10,  32,   9, 121])

In [85]:
data1[data1 == 23]

array([], dtype=int32)

In [86]:
data1[data1 > 60]

array([ 63, 173, 121])

In [87]:
# Logical Operations
# and ---- &
# or ----- |
# not ---- !
data1[ (data1 > 150) & (data1 < 180) ]

array([173])

# BuiltIn Mathematical Functions

In [88]:
data1 = np.random.randint(1,200,9)
data1

array([  7, 139, 183, 161, 164, 112, 111, 130,   2])

In [89]:
np.sqrt(data1)

array([ 2.64575131, 11.78982612, 13.52774926, 12.68857754, 12.80624847,
       10.58300524, 10.53565375, 11.40175425,  1.41421356])

In [90]:
np.sin(data1)

array([ 0.6569866 ,  0.69608013,  0.70868041, -0.70240779,  0.59493278,
       -0.8899956 , -0.86455145, -0.93010595,  0.90929743])

In [91]:
np.cos(data1)

array([ 0.75390225,  0.7179641 ,  0.70552964, -0.71177476,  0.80377546,
        0.4559691 , -0.50254432, -0.36729133, -0.41614684])

In [92]:
np.exp(data1)

array([1.09663316e+03, 2.32773204e+60, 2.99150814e+79, 8.34471649e+69,
       1.67608111e+71, 4.37503945e+48, 1.60948707e+48, 2.87264955e+56,
       7.38905610e+00])

In [93]:
np.exp(np.array([0]))

array([1.])

In [94]:
np.log(data1)

array([1.94591015, 4.93447393, 5.20948615, 5.08140436, 5.09986643,
       4.71849887, 4.7095302 , 4.86753445, 0.69314718])